language: android

android:
  components:
    - tools
    - platform-tools
    - build-tools-25.0.3
    - android-25

jdk:
  - oraclejdk8
  
install:
  - true

before_script:
  - chmod +x gradlew      #Grand permissions

script: TERM=dumb ./gradlew assembleDebug -x connectedCheck
